Include domain validation field
sonr-io/react-native-ui-components pull request #32
Opened 2022-07-22 17:17 UTC by hvhallmann

Include domain validation field with sonr/validation package.
Please check if the package is working on your machine, I have the feeling it wasn't well published.

## Changes

- Create new input field to deal with user domain
- User sonr/validation
- remove domain from common text input

## API Updates

### New Features *(required)*

Asks the package to deal with validation

### Deprecations *(required)*

FieldWithIcon component does not deal with Domain anymore

## References *(optional)*

https://www.npmjs.com/package/@sonr-io/validation

2022-07-25 14:46 UTC, tgfassina requested changes

2022-07-25 14:46 UTC, tgfassina commented on src/components/FieldDomain.tsx
> +        {warning ? <WarningOutline style={styles.warningIcon} /> : null}
These svg's shouldn't receive properties, and be treated just as images. This style can be added to the container of the icon

2022-07-25 14:46 UTC, tgfassina commented on src/components/FieldWithIcon.tsx
> -const getStyles = (lightTheme: boolean, domain: boolean) =>
👍🏻

2022-07-25 14:46 UTC, tgfassina commented on src/components/FieldDomain.tsx
> +export default FieldDomain;
Is this being used somewhere? I couldn't find it

2022-07-25 15:11 UTC, hvhallmann commented on src/components/FieldDomain.tsx
> +export default FieldDomain;
I didn't include on the PromptRecognized(first screen) because I was not sure if
**Wallet Address or .snr Domain**
is the same as just .snr Domain. So, I included a story for that, FieldDomain
Let me know if we can replace the one at PromptRecognized

2022-07-25 15:12 UTC, hvhallmann commented on src/components/FieldDomain.tsx
> +        {warning ? <WarningOutline style={styles.warningIcon} /> : null}
If I change the color of container to red, it will reflect on the SVG?
ok, I will try it

2022-07-25 15:18 UTC, tgfassina commented on src/components/FieldDomain.tsx
> +        {warning ? <WarningOutline style={styles.warningIcon} /> : null}
It won't change it. If the reason for that is changing the icon color, then we can pass the color as a property instead of the whole style object. But I'm also not against doing 2 different icons

2022-07-25 15:21 UTC, tgfassina commented on src/components/FieldDomain.tsx
> +export default FieldDomain;
I think we can use it for login and create account no problem

2022-07-25 17:58 UTC, hvhallmann commented on src/components/FieldDomain.tsx
> +        {warning ? <WarningOutline style={styles.warningIcon} /> : null}
ok, my mistake,
 was not about the color,
fixed

2022-07-25 17:59 UTC, hvhallmann commented on src/components/FieldDomain.tsx
> +export default FieldDomain;
ok, changed 
looks good

2022-07-29 17:14 UTC, tgfassina approved these changes

2022-07-29 17:14 UTC, merged